#!/bin/sh

# Creates a link to a global .ycm_extra_conf.py in the root directory.
# This configuration file is specialised for a compile_commands.json exported
# by CMake in the 'build' folder.
# It is assumed that set(CMAKE_EXPORT_COMPILE_COMMANDS ON) is in the
# CMakeLists.txt file.

project_root="$(git rev-parse --show-toplevel)"

if [   -e "${project_root}/CMakeLists.txt"     ] &&
   [ ! -e "${project_root}/.ycm_extra_conf.py" ]; then
  ln -s "${GIT_DIR}/hooks/ycm_extra_conf.py" "${project_root}/.ycm_extra_conf.py"
fi
