#!/bin/sh

# Invoked by methods that rewrite commits:
# - git commit --amend
# - git rebase

COMMAND_USED="$1"

hooks_path="$(git config core.hooksPath || echo "${GIT_DIR}/hooks")"

case "${COMMAND_USED}" in
  rebase)
    exec "${hooks_path}/post-merge"
    ;;
esac
