#!/bin/sh

# This hook is invoked after 'git checkout' succeeds.
# Note this also applies after a 'git clone'.

"$(dirname "${0}")/create-tags-file" &
"$(dirname "${0}")/clean-python-bytecode-files" &
"$(dirname "${0}")/link-ycm-extra-conf" &
