#!/bin/sh

# This hook is invoked after 'git checkout' succeeds.
# Note this also applies after a 'git clone'.

"$(dirname "${0}")/scripts/create-tags-file" &
"$(dirname "${0}")/scripts/clean-python-bytecode-files" &
